DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS security;
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS match;
DROP TABLE IF EXISTS record;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE security (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE "order" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL,
  side TEXT NOT NULL,
  security_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (security_id) REFERENCES security (id)
);

CREATE TABLE match (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sell_id INTEGER NOT NULL,
  buy_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  FOREIGN KEY (sell_id) REFERENCES "order" (id),
  FOREIGN KEY (buy_id) REFERENCES "order" (id)
);

CREATE TABLE record (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL,
  payload TEXT,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
